# Generated by Django 4.1 on 2022-09-22 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='students',
            old_name='id',
            new_name='student_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.department'),
        ),
    ]
